# This file is managed by 'repo_helper'. Don't edit it directly.
---

language: python
dist: focal
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'

arch:
  - amd64
  - arm64
install:

  - pip install --upgrade pip
  - pip install tox tox-travis
  - pip install coveralls coverage_pyver_pragma

script:
  - tox -vv
after_success:
  - coveralls


stages:
  - test
  - deploy_pypi


jobs:
  allow_failures:
    - arch: arm64

  exclude:
    - python: '3.7'
      arch: arm64
    - python: '3.8'
      arch: arm64

  include:
    - stage: test
      dist: bionic
      python: 3.8

    - stage: deploy_pypi
      python: "3.6"
      script: skip
      deploy:
        on:
          tags: true
          repo: domdfcoding/octocheese
        provider: pypi
        user: "DomDF"
        password:
          secure: YKkBhXfskrAOLYCSA6rAEVm3F0kkCxNEl075TnYdoA56rabZQhGMrSBx9dGDz4c1Aj/gM7uomVgQ/Sv1t9nU1zIwC2FS7+qH4S7K/hsdi3T6IX8P65yPxOtGz4G99vbVoEc9u6U+aJmvJReuE2xtc1vidAWE3OLIF3KcO5gU/FkfWmcheVyem9WCNZocWoUYfMeEvayrMvl4HqlP+6lR3q0opuCrQCvZt6R857ncTgbj0nbMoG+6dWCC1FJ6Jq9/cgVfYPIhaDsRdbyzNWlutDrKw2vqIDAU2GDRa0ekIhMTHuVXI+yA9XIyHL4q02UQ/mcEg+t58rt7jqcKUyuQ2y/bD2YkaFFc+eptcWEeKn7IW2h/y4Hunzd30pggQt0a4SSGuGo5vpF+2D/m3128rd2vI3IQT2kNqpbl6jCTtJWSTX9eZhQdXJQpywjxLVT2kU32pZru7eIpNVHI1fhkcQl6tJhZUKyQRfpgPBCovzo6HadEav+4fSGSL/+BL+FkXTWf8TzP89M3YISbGy7As1hezoLszzxmm/VLGXUwJV2S3tLVUX1i92J5IoXQ/Ifvu3vybtZOtBz85SPSSfZZ3RDlZbaH4abT8+pMCqE8XN6X7sEA0VirNgKJRS1sLhuVq1YfVbNTjO/Xyi9UZrHGAzjtQImL6NxF+Eyql2juXu0=
        distributions: "sdist bdist_wheel"
        skip_existing: true
