name: 'copy_pypi_2_github'
description: 'Copy PyPI Packages to GitHub Releases'
author: 'Dominic Davis-Foster'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  pypi_name:
    description:
      The name of the project on PyPI.
    required: true
  repository:
    description:
      The GitHub repository to copy the files to. By default this is the repository running the action. Must be in the format <username>/<repo_name>
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'