name: 'octocheese'
description: 'Copy PyPI Packages to GitHub Releases'
author: 'Dominic Davis-Foster'
branding:
  icon: 'box'
  color: 'blue'
inputs:
  pypi_name:
    description:
      The name of the project on PyPI.
    required: true
  max_tags:
    description:
      The maximum number of tags to process, starting with the most recent. Set to -1 to process all tags.
    default: "-1"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
